<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('applications', function (Blueprint $table) {
            $table->id('application_id');
            $table->string('reference_no')->unique()->nullable(); // generated by clerk
            $table->foreignId('developer_id')->constrained('developers', 'developer_id');
            $table->string('tajuk');
            $table->text('lokasi');
            $table->string('no_fail');
            $table->string('status')->default('RECORDED');
            $table->foreignId('officer_id')->nullable()->constrained('users', 'user_id');
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('applications');
    }
};
